### ISSUE TITLE
Unparse vs Pretty

### ISSUE THREAD

**Issue by dimalypai** [bvdelft/paragon#4]
I think we should clarify what is the purpose for each of them in comments. I am not sure I understand this completely.

**Comment by bvdelft** [comment]
I believe we said Unparse => revert to original paragon syntax, Pretty => show readable ast node as in haskell datastructure

**Comment by dimalypai** [comment]
So to go further: Unparse => for users (in error messages) and for code printing in code generation, Pretty => cleaned up debugging representation for developers, deriving Show => full Haskell representation. Right?

**Comment by bvdelft** [comment]
Yes :)

**Comment by dimalypai** [comment]
Added clarifying comments in c927605 and to the Wiki page (Warnings and Advices).
