### ISSUE TITLE
Construction of partial ASTs for testing

### ISSUE THREAD

**Issue by bvdelft** [bvdelft/paragon#5]
See also the comment in issue https://github.com/bvdelft/paragon/commit/a5698f3311bddb9fb1bb78599451227103f1eaef.

When writing tests I often need to modify the AST or partially build one. I wrote some helper functions to do so, but I was wondering if there is perhaps an easier way? Or perhaps we can somehow create a module that can be shared by the test modules, in which we collect a bunch of these AST helpers?

See the bottom of this file for example helpers: https://github.com/bvdelft/paragon/blob/a5698f3311bddb9fb1bb78599451227103f1eaef/test/Language/Java/Paragon/NameResolutionSpec.hs

**Comment by dimalypai** [comment]
I think that all this ASTModifier business is quite handy. Yes, maybe having a separate module with these helpers ready would be nice.

**Comment by bvdelft** [comment]
Created separate module in commit c8a2a87bd8f28dffe0687e8a1bf115c3b68e2438
